// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import edu.stanford.nlp.pipeline.Annotation;
import edu.stanford.nlp.pipeline.AnnotationPipeline;
import edu.stanford.nlp.pipeline.StanfordCoreNLP;
import edu.stanford.nlp.sentiment.SentimentCoreAnnotations;
import edu.stanford.nlp.ling.CoreAnnotations;
import java.util.Properties;

public class SentimentClassification_Java extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Review;

	public SentimentClassification_Java(IContext context, java.lang.String Review)
	{
		super(context);
		this.Review = Review;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Properties props = new Properties();
        props.setProperty("annotators", "tokenize, ssplit, parse, sentiment");
        StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
        String inputText = Review;
        Annotation annotation = new Annotation(inputText);
        pipeline.annotate(annotation);
        String sentiment = annotation.get(CoreAnnotations.SentencesAnnotation.class)
                                    .get(0)
                                    .get(SentimentCoreAnnotations.SentimentClass.class);
        
        String output=sentiment;
        return output;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SentimentClassification_Java";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
